dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink@1.1.0
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink@1.1.0"

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

networks:
  mainnet-fork-dev:
    eth_usd_priceFeed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False

  rinkeby:
    eth_usd_priceFeed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True
  development:
    verify: False
  ganache-local:
    verify: False
